cloud:
  aws:
    credentials:
      access: AKIAT4FGO43SC427JJKR
      secret: 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
      region: ap-southeast-3
spring:
  application:
    name: guluguluapp
gulugulu:
  crypto:
    saltformat: A4GxlHFcmS%spsvcz7q8BN
  jwt:
    secret: TpVsBJhfWmO99pWhppnmrNfcGRtLXGeNb2Pz9vAuQb8QjxBqzABc1o74BBQI