cloud:
  aws:
    credentials:
      access: access
      secret: secret
      region: ap-southeast-3
spring:
  application:
    name: guluguluapp
gulugulu:
  crypto:
    saltformat: A4GxlHFcmS%spsvcz7q8BN
  jwt:
    secret: TpVsBJhfWmO99pWhppnmrNfcGRtLXGeNb2Pz9vAuQb8QjxBqzABc1o74BBQI